import type { Certification } from "./types";

export const certifications: Certification[] = [
	{
		title: "珠算検定 四段",
		issuer: "全国珠算教育連盟",
		acquiredAt: "2014年4月",
		expiresAt: "無期限",
		color: "purple",
		icon: {
			src: "/image/certification/abacus.jpeg",
			width: 225,
			height: 225,
			alt: "全国珠算教育連盟",
		},
	},
	{
		title: "実用英語技能検定 2級",
		issuer: "日本英語検定協会",
		acquiredAt: "2018年6月",
		expiresAt: undefined,
		color: "yellow",
		icon: {
			src: "/image/certification/eiken.png",
			width: 1200,
			height: 1200,
			alt: "公益財団法人日本英語検定協会",
		},
	},
	{
		title: "ITパスポート",
		issuer: "情報処理推進機構",
		acquiredAt: "2022年4月",
		expiresAt: undefined,
		color: "blue",
		icon: {
			src: "/image/certification/ipass.png",
			width: 868,
			height: 817,
			alt: "ITパスポート",
		},
	},
	{
		title: "ジェネラリスト検定",
		issuer: "日本ディープラーニング協会",
		acquiredAt: "2023年3月",
		expiresAt: undefined,
		color: "blue",
		icon: {
			src: "/image/certification/generalist.png",
			width: 800,
			height: 800,
			alt: "ジェネラリスト検定",
		},
	},
	{
		title: "基本情報技術者試験",
		issuer: "情報処理推進機構",
		acquiredAt: "2023年5月",
		expiresAt: undefined,
		color: "blue",
		icon: {
			src: "/image/certification/ipa.jpg",
			width: 1280,
			height: 670,
			alt: "情報処理推進機構",
		},
	},
	{
		title: "TOEIC L&R 960点",
		issuer: "国際ビジネスコミュニケーション協会",
		acquiredAt: "2023年8月",
		expiresAt: undefined,
		color: "yellow",
		icon: {
			src: "/image/certification/toeic.jpg",
			width: 430,
			height: 199,
			alt: "TOEIC",
		},
	},
	{
		title: "応用情報技術者試験",
		issuer: "情報処理推進機構",
		acquiredAt: "2024年7月",
		expiresAt: undefined,
		color: "blue",
		icon: {
			src: "/image/certification/ipa.jpg",
			width: 1280,
			height: 670,
			alt: "情報処理推進機構",
		},
	},
	{
		title: "ゆめみパスポート",
		issuer: "株式会社ゆめみ",
		acquiredAt: "2025年2月",
		expiresAt: "2028年2月",
		color: "cyan",
		icon: {
			src: "/image/certification/yumemi.jpg",
			width: 335,
			height: 335,
			alt: "株式会社ゆめみ",
		},
	},
	{
		title: "資産運用検定3級",
		issuer: "資産運用検定協会",
		acquiredAt: "2025年3月",
		expiresAt: undefined,
		color: "emerald",
		icon: {
			src: "/image/certification/amc.png",
			width: 104,
			height: 102,
			alt: "資産運用検定協会",
		},
	},
];
